### ISSUE TITLE
Issue with CaffeCoder

### ISSUE THREAD

**Issue by AnneLaureM** [robotology/himrep#22] opened 2016-10-12 16:57 UTC
Hi 

We have difficulties to compile CaffeCoder on the Cuda blade on the cluster.
I get the following error:

`LD -o .build_release/lib/libcaffe.so.1.0.0-rc3
/usr/bin/ld: /usr/local/lib/libgflags.a(gflags.cc.o): relocation R_X86_64_32S against`.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libgflags.a: could not read symbols: Bad value
collect2: error: ld returned 1 exit status
make: **\* [.build_release/lib/libcaffe.so.1.0.0-rc3] Error 1`

I have tried with cmake and directly with Makefile.config. And I have already add '-fPIC'. I have already added '-fPIC'.

The cmake command returns:

`icub@icub-cuda:/usr/local/src/robot/caffe/build$ cmake ..
-- Boost version: 1.49.0
-- Found the following Boost libraries:
--   system
--   thread
--   filesystem
-- Found gflags  (include: /usr/local/include, library: /usr/local/lib/libgflags.a)
-- Found glog    (include: /usr/local/include, library: /usr/local/lib/libglog.so)
-- Found PROTOBUF Compiler: /usr/bin/protoc
-- Found lmdb    (include: /usr/local/include, library: /usr/local/lib/liblmdb.so)
-- Found LevelDB (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libleveldb.so)
-- Found Snappy  (include: /usr/include, library: /usr/lib/libsnappy.so)
-- CUDA detected: 7.5
-- Found cuDNN: ver. 5.1.3 found (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
-- Automatic GPU detection failed. Building for all known architectures.
-- Added CUDA NVCC flags for: sm_20 sm_21 sm_30 sm_35 sm_50
-- OpenCV found (/usr/local/src/robot/opencv/build)
-- Found Atlas (include: /usr/include, library: /usr/lib/atlas-base/libatlas.so)
-- Could NOT find NumPy: Found unsuitable version "1.6.2", but required is at least "1.7.1" (found /usr/lib/pymodules/python2.7/numpy/core/include)
-- Boost version: 1.49.0
-- Found the following Boost libraries:
--   python
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
## -- Python interface is disabled or not all required dependencies found. Building without it...

-- ******************\* Caffe Configuration Summary *******************
-- General:
--   Version           :   1.0.0-rc3
--   Git               :   rc3-270-g4ba654f-dirty
--   System            :   Linux
--   C++ compiler      :   /usr/bin/c++
--   Release CXX flags :   -O3 -DNDEBUG -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Debug CXX flags   :   -g -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
## --   Build type        :   Release

--   BUILD_SHARED_LIBS :   ON
--   BUILD_python      :   ON
--   BUILD_matlab      :   OFF
--   BUILD_docs        :   ON
--   CPU_ONLY          :   OFF
--   USE_OPENCV        :   ON
--   USE_LEVELDB       :   ON
--   USE_LMDB          :   ON
## --   ALLOW_LMDB_NOLOCK :   OFF

-- Dependencies:
--   BLAS              :   Yes (Atlas)
--   Boost             :   Yes (ver. 1.49)
--   glog              :   Yes
--   gflags            :   Yes
--   protobuf          :   Yes (ver. 2.4.1)
--   lmdb              :   Yes (ver. 0.9.15)
--   LevelDB           :   Yes (ver. 1.5)
--   Snappy            :   Yes (ver. 1.0.5)
--   OpenCV            :   Yes (ver. 3.0.0)
## --   CUDA              :   Yes (ver. 7.5)

-- NVIDIA CUDA:
--   Target GPU(s)     :   Auto
--   GPU arch(s)       :   sm_20 sm_21 sm_30 sm_35 sm_50
## --   cuDNN             :   Yes (ver. 5.1.3)

-- Documentaion:
--   Doxygen           :   No
## --   config_file       :   

-- Install:
## --   Install path      :   /usr/local/src/robot/caffe/build/install

-- Configuring done
-- Generating done
-- Build files have been written to: /usr/local/src/robot/caffe/build`

Has anyone seen this error ?

Cheers,

Anne-Laure
@gregoire-pointeau

**Comment by GiuliaP** [comment] 2016-10-17 09:01
Dear @AnneLaureM ,

as I read from the reported error, you have problems in compiling Caffe and not CaffeCoder, right? If this is the case, you may also try to post your error on [Caffe Users mailing list](https://groups.google.com/forum/#!forum/caffe-users) or open a similar issue on Caffe's repository.

In any case, did you follow the instructions in the [README_Caffe.md](https://github.com/robotology/himrep/blob/master/README_Caffe.md) to build Caffe? If not, which step did you change? In particular, how did you install the Google Flags library? It seems that the problem is linking this dependency.

Did you also try following the instructions on the original [Caffe website](http://caffe.berkeleyvision.org/installation.html)?

Another thing is that if you are on Ubuntu 16.04 and use CUDA 7.5 with GCC 5.3, you should add the following:

``` cmake
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC -D_FORCE_INLINES -Wall")
```

Lastly, which GPU do you have?

Giulia

**Comment by pattacini** [comment] 2016-10-25 09:23
@AnneLaureM any news on @GiuliaP's feedback?

**Comment by pattacini** [comment] 2016-11-01 14:33
Closing for the time being.

**Comment by AnneLaureM** [comment] 2016-11-02 16:21
Hello @GiuliaP, @pattacini 

I am really sorry for this long silence (I just submit my thesis manuscript at the end of the last week ;-) ...). 
I finally found the solution today. I post it in case someone else has the same error.
I compiled caffe and himrep on the cluster configured by IIT (Debian Wheezy), on the "cuda" blade 
The main characteristics are : 
- Hardware :
  NVIDIA Corporation GK107 [Quadro K2000](rev a1)
  3D controller: NVIDIA Corporation Device 1024 (rev a1)
- Software : 
  gcc (Debian 4.7.2-5) 4.7.2
  Cuda compilation tools, release 4.2, V0.2.1221

I have tested `set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC -D_FORCE_INLINES -Wall")`without success
There are two methods to compile caffe (cmake and make). I chose cmake (I also had a lot of strange errors with make).

To fix the error : 
`LD -o .build_release/lib/libcaffe.so.1.0.0-rc3 /usr/bin/ld: /usr/local/lib/libgflags.a(gflags.cc.o): relocation R_X86_64_32S against.rodata`
I replaced in CMakeLists `Atlas_CBLAS_LIBRARY  /usr/lib/atlas-base/libptcblas.a` by the correct library on my machine :
`/usr/lib/atlas-base/libcblas.so`
Now everything is ok (caffe and himrep)

Thanks a lot @GiuliaP 

Cheers,

Anne-Laure

**Comment by pattacini** [comment] 2016-11-02 16:41
Hi @AnneLaureM 
That type of submission is always a big relief 😄 

Remember that `cmake` is alternative to `configure`, somehow, not to `make` because serves different purposes.

Anyway, you're saying that you made use of the dynamic library rather than the static one. It's somewhat strange that those info are hard-coded within the `CMakeLists.txt` file without resorting to a `find_package` directive.

@GiuliaP do you reckon everything is ok here?

**Comment by AnneLaureM** [comment] 2016-11-02 17:09
Hi @pattacini 

> Remember that cmake is alternative to configure, somehow, not to make because serves different purposes.

Yes, sorry... , it is written like this in the caffe tutorial, I did not pay attention. (However, there is no `configure` in caffe repo, only `Makefile.config`).
I think you have absolutely right for the dynamic library. It is not a problem of static/dynamic library but just the name of the library. I am trying to recompile with the correct static library, so:
`libcblas.a` but it takes time... :-(
I will keep you informed.
Thank you very much !

Anne-Laure

**Comment by AnneLaureM** [comment] 2016-11-02 17:33
Hi @pattacini @GiuliaP 

So at the end, I have replaced `/usr/lib/atlas-base/libptcblas.a` by `/usr/lib/atlas-base/libcblas.a` (`Atlas_CBLAS_LIBRARY`) and everything is fine (caffe and himrep).
Thanks again Ugo !

Cheers,

Anne-Laure

**Comment by pattacini** [comment] 2016-11-03 10:45
If you're happy we could close this issue.
Feel free to open it again if required.

And thanks for reporting the solution!

**Closed as completed by pattacini** 2016-11-03 10:45 UTC
